# Generated by Django 5.0.2 on 2024-02-10 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_to_review', models.FileField(null=True, upload_to='code_to_review/')),
                ('restructured_code', models.FileField(null=True, upload_to='restructured_code/')),
                ('code_report', models.TextField()),
                ('temp', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
    ]
