# Generated by Django 5.0.2 on 2024-02-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='temp_files/')),
                ('upload_at', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='code',
            name='temp',
        ),
    ]
