# Generated by Django 5.0.2 on 2024-03-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_review", "0002_code_name_code_upload_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="restructured_code",
            field=models.BooleanField(default=False),
        ),
    ]
