# Generated by Django 5.0.2 on 2024-04-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0007_messages"),
        ("code_review", "0003_alter_code_restructured_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCredits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction", models.CharField(blank=True, max_length=15)),
                ("date", models.DateField(auto_now_add=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="User.profile"
                    ),
                ),
            ],
        ),
    ]
