# Generated by Django 5.0.2 on 2024-02-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(null=True, upload_to='profile_image/')),
                ('profession', models.CharField(max_length=25, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'others')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
