# Generated by Django 5.0.2 on 2024-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0003_profile_created_date_profile_credit_points_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.IntegerField(choices=[(1, "admin"), (2, "user")], default=2),
        ),
    ]
