# Generated by Django 5.0.2 on 2024-03-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="credit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
