# Generated by Django 5.0.2 on 2024-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0005_profile_credit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="credit",
        ),
    ]
